<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Taks_2" Id="{3f954ceb-7654-4c46-82ae-7c4cd977fac6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Taks_2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Taks_2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>